# Generated by Django 4.1.5 on 2023-01-05 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Elements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("price", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=50, unique=True)),
                ("order_qty", models.IntegerField()),
                ("order_price", models.FloatField()),
                ("delivery_fees", models.FloatField()),
                ("total_payment", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Resturants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("phone_number", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("phone_number", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=100)),
                ("gender", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="OrdersElements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.IntegerField()),
                (
                    "elements",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.elements"
                    ),
                ),
                (
                    "orders",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.orders"
                    ),
                ),
                (
                    "users",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.users"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="orders",
            name="assignee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="polls.users"
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="resturant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="polls.resturants"
            ),
        ),
        migrations.AddField(
            model_name="elements",
            name="resturant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="polls.resturants"
            ),
        ),
    ]
