# Generated by Django 4.1.5 on 2023-01-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resturants",
            name="logo",
            field=models.ImageField(default=None, upload_to="images/"),
            preserve_default=False,
        ),
    ]
