# Generated by Django 4.1.5 on 2023-01-13 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0003_remove_orderselements_users_orderselements_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="orders", name="order_number",),
        migrations.AddField(
            model_name="orders",
            name="created_at",
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orders",
            name="assignee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="delivery_fees",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="orders", name="order_price", field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="orders", name="order_qty", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="orders",
            name="total_payment",
            field=models.FloatField(null=True),
        ),
    ]
