# Generated by Django 4.1.5 on 2023-01-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_remove_orders_order_number_orders_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="state",
            field=models.CharField(
                choices=[(1, "Completed"), (2, "Ongoing"), (3, "Cancelled")],
                default=None,
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
