# Generated by Django 4.1.5 on 2023-01-14 21:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0007_alter_votes_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="votes", unique_together={("user", "restaurant")},
        ),
        migrations.RemoveField(model_name="votes", name="order",),
    ]
