# Generated by Django 4.1.5 on 2023-01-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0008_alter_votes_unique_together_remove_votes_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="state",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("Ongoing", "Ongoing"),
                    ("Cancelled", "Cancelled"),
                ],
                max_length=50,
            ),
        ),
    ]
