# Generated by Django 4.1.5 on 2023-01-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0009_alter_orders_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="order_num",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
